### ISSUE TITLE
Extend the use of LIGO failwith to pairs

### ISSUE THREAD

**Issue by pasqu4le** [tqtezos/baseDAO#106]
# Clarification and motivation

In the LIGO version of the contract we always use `failwith` with a single string, however we'd like to match the Lorentz counterpart in the use of `pair`s for some errors.

The problem is that the standard `failwith` from LIGO only supports a few input types, but not `pair`s, however we can define our own specialized version of `failwith` using embedded Michelson (see [here](https://github.com/tqtezos/stablecoin/blob/master/ligo/stablecoin/actions.ligo#L717-L726)).

We should likely add this to `types.mligo` because this will be used by many modules and the `types` is safely imported by all of them.
Note: It looks like we'll need to declare it for a specific pair type, so we might need to have more than one version of this.

Additionally we'll need to update:
- the `specification-ligo.md` section on `Errors` because it says it always fails with a `string`
  note: we can copy the line to change from the Lorentz specification
- the shared tests introduced in #99, which needed to make a differentiation with the `IsLorentz` because of the different errors.

# Acceptance criteria

- `failwith` equivalent function(s) to throw as many `pair` errors as in the Lorentz version are added to LIGO's code.
- tests and documentation are updated accordingly.

**Comment by rinn7e** [comment]
> We should likely add this to `types.mligo` because this will be used by many modules and the types is safely imported by all of them.

With our use case, it not really possible to share the fail function, since we annotate `failwith` with different types. e.q.

```
(failwith ("FROZEN_TOKEN_NOT_TRANSFERABLE"): token_id)
(failwith("NOT_OWNER"): storage)
```

In this two fail cases, we will need this function:

```ocaml
  let fail_unit: (string * unit -> _) =
      [%Michelson ({| { FAILWITH } |} : string * unit -> _)] in
```

But since they have different types, we can't use the shared function, and have to use the michelson code directly where it is needed like this:

```
([%Michelson ({| { FAILWITH } |} : string * unit -> token_id)]
  ("FROZEN_TOKEN_NOT_TRANSFERABLE", ()) : token_id)

([%Michelson ({| { FAILWITH } |} : string * unit -> storage)]
  ("FROZEN_TOKEN_NOT_TRANSFERABLE", ()) : storage)
```

There is really no ideal way to make this sharable. @pasqu4le What's your view on this, Pasquale?

**Comment by pasqu4le** [comment]
@rinn7e I didn't think about the need for a fixed return type.

I tried to see if there was some workaround using the C pre-processor but it doesn't seem possible to make this a macro or function that can be shared.

We'll need to resort to use the type-annotated Michelson code everywhere, as you suggested.
