### ISSUE TITLE
Add a new RegistryDAO proposal type that can push values to target contract(s)

### ISSUE THREAD

**Issue by gromakovsky** [tqtezos/baseDAO#137]
# Clarification and motivation

We need to extend RegistryDAO with an additional proposal type.
> The proposals with addresses are diff’s to the list of parameter-receiver contract list
> If we want to pin down the diff-type, it can be `pair (list %remove address) (list %add address)` - it’s roughly `updateTransferlist` from TZIP-15

Currently there is no "parameter-receiver contract list", so apparently we should add one.

# Acceptance criteria

1. Both implementations (LIGO and Lorentz) are updated to have the new type of proposal. It should update some list of addresses. Apparently this list should be added to the contract first, it's not clarified yet.
2. Specification of RegistryDAO is updated.
3. Tests for new functionality are present.

**Comment by gromakovsky** [comment]
As far as I understand this task, we need to extend RegistryDAO storage to contain a set of addresses and have a proposal type that would update this set (by adding/removing lists of addresses). @obstropolos what should we do with this list apart from merely storing it?

**Comment by michaeljklein** [comment]
@gromakovsky: Yes, for this feature we'll need to:
- Store `list address`: the list of successful-proposal receiver contract addresses
- Add proposal type, either:
  * Two proposal types: `add_receivers : list address`, `remove_receivers : list address`
  * One proposal type: `receiver_diff : pair (list %remove address) (list %add address)`
  * (whichever results in a smaller contract)
- Support a TZIP-16 view function to read the list off-chain

**Comment by sras** [comment]
> Store list address: the list of successful-proposal receiver contract addresses

@michaeljklein Does the addresses have to be stored in a `list`, or can a `set` work fine as well?

**Comment by michaeljklein** [comment]
@sras sure: its storage type shouldn't particularly matter: whatever's the smallest
