### ISSUE TITLE
Implement proposals and voting logic with tests

### ISSUE THREAD

**Issue by gromakovsky** [tqtezos/baseDAO#14]
# Clarification and motivation

After #5 and #6 we will have FA2 entrypoints, but there are more in the specification. We should implement them as well.
In this issue let's focus on proposals and voting.

# Acceptance criteria

The following entrypoints are implemented and tested:
* `propose`
* `proposal_metadata`
* `set_voting_period`
* `set_quorum_threshold`
* `vote`
* `flush`

Note that there are two complications:
1. #5 is not merged yet, so there is no contract to extend (I don't count `Basic.hs` because it's a stub). But #5 is close to finish, I hope it will be merged today or tomorrow.
2. The specification is not approved yet, maybe there will be some changes in it.

I hope we can still start working on this issue now, but please keep these facts in mind.

**Comment by rinn7e** [comment]
@gromakovsky I'm currently in the process of defining the `Storage` of baseDAO. I have this:

```haskell
type ProposalStatus = Ongoing | Ended

data Storage proposalMetadata = Storage
  { ...
  , sProposals :: BigMap (ProposalId, ProposalStatus) Proposal
  , sRejectedProposals :: BigMap ProposalId Proposal
  , sAcceptedProposals :: BigMap ProposalId Proposal
  }
```

I'm thinking of when calling `flush` it will moved all the proposals with key: `(_, Ended)` to `sRejectedProposals` or `sAcceptedProposals` depends whether it got accepted or not.

One problem is that, how do we mark a proposal with `Ended` status in the first place. I'm not sure if it is possible to have a have a function which for example, run every 5mn to mark an ongoing proposals with ended status.

If it is not possible, we can implement it without `Ended` status, by using `sProposals :: BigMap (ProposalId, StartDate) Proposal`, and whenever `flush` is called, it check the start dates with the configured duration of a proposal, moved all the proposals that pass the deadline, and do the rest of distributing back the frozen tokens.

Hope to get your advice whether or not it is possible to run a cron-like function and your thought on the above solution, Ivan.

**Comment by gromakovsky** [comment]
I think it's impossible to have a function that runs every `x` minutes. That's why we need `flush`. If it was possible, flushing would happen automatically as part of this function. I think we don't need to store expired proposals. If voting on a proposal ends and it's flushed, we can apply it (if it's accepted) and forget about it.

> If it is not possible, we can implement it without Ended status, by using sProposals :: BigMap (ProposalId, StartDate) Proposal, and whenever flush is called, it check the start dates with the configured duration of a proposal, moved all the proposals that pass the deadline, and do the rest of distributing back the frozen tokens.

The problem here is that you can't get a range of values from a `BigMap`. We can store `ProposalId`s sorted by `StartDate` in a list, for example. Unlike `BigMap`s, lists support iteration. And I think it's ok to assume there won't be too many proposals to make `[ProposalId]` list too large.

**Comment by rinn7e** [comment]
> The problem here is that you can't get a range of values from a `BigMap`. We can store `ProposalId`s sorted by `StartDate` in a list, for example. Unlike `BigMap`s, lists support iteration. And I think it's ok to assume there won't be too many proposals to make `[ProposalId]` list too large.

I see, that makes a better solution. Thanks Ivan, I'll make the change accordingly.

**Comment by rinn7e** [comment]
> I think we don't need to store expired proposals. If voting on a proposal ends and it's flushed, we can apply it (if it's accepted) and forget about it.

On another note, it is probably useful to be able to see rejected/accepted proposals. I guess if we do not store them on-chain, they should be store off-chain.

Is there a recommended way to provide information to be stored off-chain, Ivan?

**Comment by gromakovsky** [comment]
I think it's better to ask what is preferred (to store them on-chain or off-chain), but I'd like to get initial feedback on our specification first, because there is quite a lot of information to process already. So I think for now we can throw it away, and hopefully soon we'll know what's preferred.

**Comment by rinn7e** [comment]
> I think it's better to ask what is preferred (to store them on-chain or off-chain), but I'd like to get initial feedback on our specification first, because there is quite a lot of information to process already. So I think for now we can throw it away, and hopefully soon we'll know what's preferred.

Sure, Ivan. I'll just implement a placeholder for now, and then adapt to the change after we got the feedback.
