### ISSUE TITLE
Implement typescript SDK

### ISSUE THREAD

**Issue by pasqu4le** [tqtezos/baseDAO#141]
# Clarification and motivation

We need to implement a typescript SDK `basedao.ts` to interact with the contract.
The requirements are as follows:
> - NPM install documentation, with a simple working example for every function
> - We need a library with all of the different ways to call the contract such as
> 1. Recognition function ('is this the DAO that I'm looking for?')
> 2. Type definitions for all the parameters
> 3. Individual functions to call each major function (`vote`, `wrap`, `unwrap`, etc.)

Note: it may be too complex to develop this all in the span of a single issue.
If possible we should try to solve this with a single PR and divide the commits in a way that's easy to follow, otherwise make multiple PRs.

# Acceptance criteria

A `basedao.ts` typescript SDK is implemented and documented.

**Comment by sras** [comment]
>Recognition function ('is this the DAO that I'm looking for?')

We would like to have a bit more information about this requirement. Basically we would like to have a more detailed use case, like how people will actually use this feature, what information they will provide as an input to this procedure, what the expected output is, etc.

**Comment by pasqu4le** [comment]
cc @michaeljklein 

The problem is that given that `baseDAO` is a template others can create contracts very similar to each other.

So if the idea is to confirm to a user that a DAO is indeed of a specific type (e.g. a `RegistryDAO`) basing the recognition of a deployed DAO on what makes it "unique" is not qute doable.

But perhaps the use case is indeed a different one.

**Comment by michaeljklein** [comment]
Hi @pasqu4le @sras, for the purpose of recognition, we want to recognize that the _entrypoint and storage types_ are compatible.

The intended use case is interacting with the DAO using Taquito in a webapp:
- The app will need to validate that the parameter and storage types match what's expected, which makes it easier to deploy the app with different contracts
- It will likely need to access elements of the storage through the API, e.g. configuration parameters
- The parameter definitions in typescript will not only be used to call the DAO, but also to extract elements of previous calls, e.g. "Does the parameter from this call to the DAO represent the creation of a proposal to _"?

If someone wants to check the code itself, they should be able to use the template with known constants to regenerate the code and compare it against the originated version.
