### ISSUE TITLE
Store more info for RegistryDAO

### ISSUE THREAD

**Issue by pasqu4le** [tqtezos/baseDAO#151]
# Clarification and motivation

There are some new requested changes for RegistryDAO, since they are relatively small and should be done soon I am grouping them all together:

1. ~~add a `name` and `description` field associated to each proposal~~
2. ~~add a description text field for transfers (for both kind) to be stored on the contract~~ Edit: no longer required
3. from the `voters` field of each stored `proposal` it should be possible to determine if the voter voted against or for it

# Acceptance criteria

The 3 requested points above are implemented for both the Lorentz and LIGO version of the contract.

**Comment by pasqu4le** [comment]
Note: since the additional info in the proposal will affect cost calculations we should modify the RegistryDAO proposal check to not account for them, see [this discussion](https://serokell.slack.com/archives/C019PCGKTK2/p1613670767007100?thread_ts=1613654280.004200&cid=C019PCGKTK2).

Also, the point 3 will need a change in `baseDAO` itself, so it won't only affect RegistryDAO

**Comment by michaeljklein** [comment]
Hi @pasqu4le, the `name` and `description` or any other proposer-chosen `string` fields in a proposal (unless it's the key/value in RegistryDAO) should be stored off-chain using TZIP-16 metadata. Otherwise, moderation functionality may be needed to manage incoming proposals from arbitrary users.

**Comment by pasqu4le** [comment]
:ok_hand: Updated the description to only make the `voters` change instead. 

Currently there's `agora_post_id` to carry off-chain metadata, if/when it's decided to switch to a different method we'll make a new issue.
