### ISSUE TITLE
Remove unnecessary nat views

### ISSUE THREAD

**Issue by pasqu4le** [tqtezos/baseDAO#166]
# Clarification and motivation

We currently have two `nat` views that are not necessary: `get_total_supply` and `get_vote_permit_counter`.
Both these views main use is for testing, which could be replaced.

More importantly these pose a potential security risk in case a `DAO` contract has the administrator role in another `DAO` or it's administrator of itself, in which voting period and quorum threshold can be changed by anyone.

These could have been just removed if #31 was ready, but that's not the case.
So, to update our tests accordingly for the moment we can (from best to worst):
1. avoid to check those values directly altogether (but keep the test indirectly as we do for other ones).
2. move the tests that depend on these to the integrational engine only.
3. replace them with `void`s and use those instead.

# Acceptance criteria

1. Tests are updated depending on which one of the solutions above is possible
2. Both on-chain views,  `get_total_supply` and `get_vote_permit_counter` are removed from the contract

Note: this issue affects both the Lorentz and Ligo version of the contract.

**Comment by kkirka** [comment]
Indeed, all the options are not ideal (but still better than views, ofc):
1. Indirect checks may yield false success, e. g., when two buggy functions produce a correct result.
2. Integrational test engine has different syntax and, well, doesn't support network tests. Rewriting the tests to the integrational engine would require some effort but eventually we'll need to rewrite these tests back to nettest, which would also require some effort. If #31 is going to be done "soon" then we can just git revert, ofc, and if it isn't, the tests may evolve too far. So this should be considered.
3. A void entrypoint occupies space that isn't free. Thanks to it being in a big map, it doesn't influence the execution cost of other entrypoints, but still.

My personal take on this is that we should go with option 3.
