### ISSUE TITLE
Implement migration

### ISSUE THREAD

**Issue by gromakovsky** [tqtezos/baseDAO#17]
# Clarification and motivation

The administrator should be able to _migrate the DAO_. Currently we propose a simple way to do it: to have a `migrate` entrypoint accepting a single address. This address is supposed to refer to the new contract instance. After a successful `migrate` call the contract enters the "migrated" state permanently, operations can't be performed anymore.

However, this proposed approach has not been approved yet, so we shouldn't start this issue yet.

# Acceptance criteria

A migration approach (maybe not the currently proposed one) is approved, implemented in our code and covered with tests.

**Comment by itkach** [comment]
A standard general comment from smart contract auditors is that single step control transfers are error-prone and dangerous and their recommendation is invariably to replace it with at least a two step implementation where recipient of control must accept it. It probably makes sense to skip naive implementation that won't survive an audit.

**Comment by gromakovsky** [comment]
Few additions to the specification based on the above comment and [this (private) thread](https://tocquevillegroup.slack.com/archives/C01BTEPMY5U/p1602510887000200):
1. After `oldDao.migrate(newDao)` is called we should expect `newDao` to call `oldDao.confirmMigration()`. Until it's done, we don't consider `oldDao` to be migrated. If `migrate` is called with a wrong address, it can be fixed by calling `migrate` again with the correct address. Note that we need to add `confirmMigration` entrypoint.
2. Let's specify that after the contract is migrated, all operations fail with `("MIGRATED", KT1NewDAO)` pair. `KT1NewDAO` is the address that was passed to `migrate`.
3. It should be possible to move associated funds:
  * We should move all XTZ, I see several ways: require that `BALANCE` is 0 (i. e. move funds in advance), automatically move them to `newDAO` (then we require `newDAO` to have an entrypoint with `()` type), pass another address to `migrate` and/or `confirmMigration`. However, it seems that currently we don't do anything with XTZ, so maybe we should just prohibit transferring XTZ to the contract.
  * We should move all FA2 tokens. I suppose there is no way to do it from the contract (it doesn't know which FA2 tokens it has). So I think we can permit `transfer_contract_tokens` to be called after migration.

Let's start with updating the specification according to these suggestions.

**Comment by sras** [comment]
@gromakovsky Have raised a draft PR with updated specification.
