### ISSUE TITLE
Grammar

### ISSUE THREAD

**Issue by Davidux1** [tqtezos/baseDAO#177]
# Clarification and motivation

Fix grammar errors in intro below by removing a duplicate instance of 'enables' from the first sentence and 'the' immediately after 'The framework enables...'

"BaseDAO is a generic smart contract framework on Tezos that enables enables a community to collectively govern resources, registries, or rules. The framework enables the a creator to customize their DAO based on a number of attributes, and uses a ‘decision lambda’ to specify arbitrary code that can be governed by a DAO’s proposals. BaseDAO also includes Permit (TZIP-17) to enable off-chain voting."

# Acceptance criteria

Verify intro paragraph 1 becomes:

"BaseDAO is a generic smart contract framework on Tezos that enables a community to collectively govern resources, registries, or rules. The framework enables a creator to customize their DAO based on a number of attributes, and uses a ‘decision lambda’ to specify arbitrary code that can be governed by a DAO’s proposals. BaseDAO also includes Permit (TZIP-17) to enable off-chain voting."

**Comment by pasqu4le** [comment]
Closing as this was caught and solved during #180
