### ISSUE TITLE
Add more assets to the auto prerelease step

### ISSUE THREAD

**Issue by pasqu4le** [tqtezos/baseDAO#198]
# Clarification and motivation

In CI we have an auto prerelease step that creates a prerelease based on master.
Currently this only includes the `baseDAO.tz` contract itself.

However, we can modify it to:
- compile all storage(s) with the default values
- generate the known metadata (for the ligo version only)

# Acceptance criteria

Both the metadata and all storage(s) with the default values are included in the automatic pre-relese by CI

**Comment by rinn7e** [comment]
> generate the known metadata (for the ligo version only)
@pasqu4le Could you explain more about this? I'm not really sure how to generate metadata (and which metadata).
