### ISSUE TITLE
Dynamic quorum percentage

### ISSUE THREAD

**Issue by michaeljklein** [tqtezos/baseDAO#207]
# Clarification and motivation

As in Tezos' voting process, it is useful to automatically update the quorum percentage based on previous participation.

# Acceptance criteria

Two storage parameters representing percentages:
- `max_change_percent`, with `default = 19%`
- `change_percent`, with `default = 5%`

Each voting stage, a `new_quorum` is calculated from the `old_quorum`
and the previous participation (`number_of_frozen_tokens_last_voting_period / known_total_supply_of_unfrozen_tokens`).

```
possible_new_quorum =
  old_quorum * (1 - change_percent) + participation * change_percent

min_new_quorum =
  old_quorum / (1 + max_change_percent)

max_new_quorum =
  old_quorum * (1 + max_change_percent)

new_quorum =
  max min_new_quorum
  (min max_new_quorum
       possible_new_quorum)
```

Note: the quorum percentage should also respect the `min_quorum_threshold`, `max_quorum_threshold` respectively.

**Comment by pasqu4le** [comment]
@michaeljklein with the BYO changes the `known_total_supply_of_unfrozen_tokens` is unknown.

There is no on-chain `get_total_supply` entrypoint in FA2 and so there is no way for us to know what the total supply of the governance token is in the external FA2 contract (unless we want to assume that this value is fixed and can be provided at origination).

 An alternative could be to track the previous `voting` period `participation` as: 
`number_of_staked_tokens_last_voting_period` / `number_of_total_frozen_tokens_in_last_voting_period`.

Where:
- `number_of_staked_tokens_last_voting_period` is the total amount of frozen tokens that were actually used to `vote` during the previous voting period
- `number_of_total_frozen_tokens_in_last_voting_period` is the total amount of frozen tokens that were available in it

**Comment by michaeljklein** [comment]
@pasqu4le Yes, as you note, there is an additional requirement:
- The DAO should store the `total_supply` of the external FA2, treating it as a constant that is set at origination.
