### ISSUE TITLE
Allow the DAO to automatically accept `admin` privileges of itself

### ISSUE THREAD

**Issue by pasqu4le** [tqtezos/baseDAO#215]
# Clarification and motivation

We currently have a two-step process for the transfer of the `admin` role:
1. `admin` calls `transfer_ownership` to create a new `admin` candidate
2. the `admin` candidate calls `accept_ownership` to get the role

This is a valuable security feature to ensure that the `admin` is not incorrectly modified to an incorrect address and to check that the new `admin` can call the contract.

However, since this is a DAO, it is supposed to be governed only by its users after an initial period, so we should be able to make the DAO accept the `admin` role of itself.

To do that I suggest modifying the `transfer_ownership` entrypoint so that if the `admin` candidate is the DAO contract itself no further calls are needed.

# Acceptance criteria

The DAO is able to automatically accept ownership of itself.

**Comment by sras** [comment]
Resolved by https://github.com/tqtezos/baseDAO/pull/226
