### ISSUE TITLE
Replace `max_vote` with `max_voters`

### ISSUE THREAD

**Issue by pasqu4le** [tqtezos/baseDAO#277]
# Clarification and motivation

Currently we have a limit on the number of votes that could be made on a proposal.
Given that:
- when possible we'd want all the possible votes to be cast
- the number of total votes is limited by the governance token (because 1 vote per token)

the only reason for this limit seems to be to avoid the issue explained in #271

However, as that explains, the problem is the potential size of the `voters` field in a `proposal` and not really the number of cast votes.

So we should switch from checking for a `max_votes` to checking for a `max_voters`, aka we should limit the `voters` field to get larger than a set value and not the `upvotes + downvotes`.

# Acceptance criteria

The contract's proposals are no longer limited by number of `votes`, but rather by number of `voters`

**Comment by sras** [comment]
It appears that changing the voters field in the proposal from a list to a map might help to reduce the size if there are multiple votes from an address. So we would like to do that as well in the context of this issue.
