### ISSUE TITLE
Refine/improve documentation

### ISSUE THREAD

**Issue by gromakovsky** [tqtezos/baseDAO#29]
# Clarification and motivation

Currently we don't have enough documentation. We have:
1. Auto generated documentation referred from `README.md`. It's quite small and doesn't even describe entrypoints.
2. `docs/specification.md` which describes what contract needs to be implemented, but doesn't really explain how to use it.
3. Trivial build and usage instructions.

# Acceptance criteria

1. Auto generated documentation is expanded and contains as much as possible. For example: storage description, description of each entrypoint.
2. There are detailed usage instructions. In particular, they should explain how to instantiate parameters of the contract. The contract we developed is a base contract for various DAOs, we should clearly explain how to implement DAOs.
3. `docs/specification.md` is proofread to match our code. Well, it may be too hard to check _everything_ carefully, but at least let's check that error scenarios and corresponding errors are accurate.

**Comment by gromakovsky** [comment]
Also we should check that all errors are present in `docs/specification.md`.

**Comment by gromakovsky** [comment]
> There are detailed usage instructions. In particular, they should explain how to instantiate parameters of the contract. The contract we developed is a base contract for various DAOs, we should clearly explain how to implement DAOs.

Note that #41 implements a more specific DAO (GameDAO).

**Comment by gromakovsky** [comment]
Part (1) is assigned to @PruStephan, he's working on it. I intended to do part (2) myself, but got sick, so I am reassigning it to @Martoon-00. I am going to add part (3), it will be for @Martoon-00 as well, he can have a fresh look.

**Comment by Martoon-00** [comment]
Let me remind that no one has checked that the entrypoints errors are enlisted correctly. 

Probably it's worth to decide who does this, or maybe better, remove that and refer to our autodoc (and then also decide which other parts in the specification we would like to deduplicate - maybe keeping specification as a list of diffs between autodoc and what we want to achieve will be simpler both for us and for readers)

**Comment by gromakovsky** [comment]
@Martoon-00 a few small leftovers for you :nate:
1. There is still one `#29` TODO left, please resolve it.
2. https://github.com/input-output-hk/haskell.nix/pull/943 got merged recently, we should repin `haskell.nix` to master.
3. FA2 metadata handling is currently not implemented, but people ask questions about metadata. Ideally we'd like to do https://github.com/tqtezos/baseDAO/issues/42 first, i. e. implement TZIP-16 metadata from the beginning rather than implement the current FA2 way (which will not be recommended soon).
