### ISSUE TITLE
Implement TZIP-16 according to TZIP-12

### ISSUE THREAD

**Issue by gromakovsky** [tqtezos/baseDAO#42]
# Clarification and motivation

See https://gitlab.com/tzip/tzip/-/merge_requests/94. Now TZIP-12 (FA2) refers to TZIP-16 and has new requirements. We should update `baseDAO` contract accordingly.

# Acceptance criteria

After https://gitlab.com/tzip/tzip/-/merge_requests/94 is merged, `baseDAO` contract should comply with the newest version of FA2.

**Comment by Martoon-00** [comment]
In this issue we should also make sure that `sTokenAddress` storage field can be initialized and later managed by the user - if it makes sense with regard to the final version of TZIP-16.

**Comment by Martoon-00** [comment]
Also note the view for counter - it will be introduced in #56 and should appear in metadata.

**Comment by Martoon-00** [comment]
How do we want to implement this?

### Put metadata in-place (as a separate deployment stage) vs in another contract

I don't consider the option of making metadata part of the contract because we are too limited.

I suppose keeping metadata in the same contract is better and not more difficult for everyone than keeping metadata separately. Probably we will have a dedicated `SetMetadata Metadata` or `UpdateMetadata (Lambda Metadata Metadata)` endpoint callable by admin, and ask the client to use it during contract origination sequence. Using `UpdateMetadata` seems more flexible in terms of possibility to apply bug fixes and in terms of fitting into operation size limit.

### How to initialize metadata?

Some fields will be provided by the client - e.g. name, homepage, we should not care about them.

Other fields are determined by us (description, version, license, authors, interfaces, errors, views). We need to decide in which format will we enlist them and how will we deliver them. Probably we could add an executable to generate all these in Yaml (or something else if they request a different format), and make CI produce an artifact with the most actual metadata.

**Comment by Martoon-00** [comment]
Also

### Do we want to provide automatically generated fields manually for now, or wait for them to be derived from doc items?

AFAIU things like errors is too tiresome to provide manually, it's easier to extract them from autodoc even if that will be a temporary solution implemented in this repository. Other metadata fields are easy to provide by hands.

**Comment by gromakovsky** [comment]
We already had to answer these questions in Stablecoin :)
1. TZIP-16 reserves several top-level fields, but it doesn't say that these fields are required, which most likely indicates that they are optional. So I wouldn't bother much trying to provide them. We have other work to do in limited time frame and we know that the current user of the contract will create storage value(s) in their code. So the purpose is to prepare our code for https://gitlab.com/tzip/tzip/-/merge_requests/94 and for Registry DAO where we want to store information about `key` and `value` types in metadata. Also we should put the name of the DAO and the description of the DAO there.
2. Putting metadata into another contract makes more sense to me. In terms of deployment complexity the difference is quite negligible: in both cases more than 1 step is required. In terms of performance, storing in a separate contract is more efficient because we don't have to add any extra entrypoints (e. g. `setMetadata`). I think metadata is supposed to stay constant (then users of the contract can use the knowledge that it's constant), but if somebody wants to be able to update it, they can add such an entrypoint into their metadata contract.

> Do we want to provide automatically generated fields manually for now, or wait for them to be derived from doc items?

Taking (1) into account, this question probably can be postponed, let's not include things like `errors` for now, they are not required and we have other work to do.

> How to initialize metadata?

Will reply later.

**Comment by gromakovsky** [comment]
Hm, btw, when I was writing it I kinda forgot this issue was about TZIP-12+TZIP-16, I thought it was simply about adding TZIP-16 here :pled:

**Comment by gromakovsky** [comment]
Btw, you may find latest discussions in [this thread](https://github.com/tqtezos/stablecoin/issues/131) useful. In particular, FA2 provides 2 ways to expose token metadata and I think it's better to do that via putting off-chain views for the `views` key.

Now to the last question:

> Other fields are determined by us (description, version, license, authors, interfaces, errors, views). We need to decide in which format will we enlist them and how will we deliver them. Probably we could add an executable to generate all these in Yaml (or something else if they request a different format), and make CI produce an artifact with the most actual metadata.

Most of these fields are optional and we could take care of them later, but views are quite necessary for TZIP-12 (after it's updated), so we should resolve this topic now. AFAIU, all these fields are put into one big JSON object. So I suppose we just need to produce a JSON object which will be merged with another JSON object by the client code. I am not sure why you suggested YAML btw if TZIP-16 requires JSON :)

So we can have a command that prints metadata as a JSON object. This JSON object can be extended by its user (e. g. one may add `description` or update `description` already present there). Since TZIP-16 will probably become used by many contracts, we can even add such a command to `ContractRegistry` (but it can be done later).

**Comment by gromakovsky** [comment]
> After https://gitlab.com/tzip/tzip/-/merge_requests/94 is merged, baseDAO contract should comply with the newest version of FA2.

I decided to keep this issue focused on TZIP-12 updates related to metadata. Created #80 to be done first. #80 will be useful not only for TZIP-12, it will let us store other metadata. And this issue (#42) can be postponed until the TZIP-12 update is merged.

**Comment by Martoon-00** [comment]
TotalSupply is to be handled elsewhere (#126), it is not mandatory for TZIP-12 support.
