### ISSUE TITLE
Make it possible to enable custom token_id

### ISSUE THREAD

**Issue by gromakovsky** [tqtezos/baseDAO#54]
# Clarification and motivation

Right now our contract always rejects all operations involving `token_id` other than 0 or 1. However, custom DAOs may have special tokens for their DAO logic. E. g. in GameDAO there can be multiple types of coins and each type may use its own `token_id`. And we may want them to be transferrable using FA2 interface.

# Acceptance criteria

A DAO developer who wants to permit FA2 operations involving `token_id` other than 0 or 1 should have an easy way to do that.

**Comment by kkirka** [comment]
1) Do I understand correctly that token ids other than 0 or 1 can only be used in transfers? e.g., I can't freeze a token of id 2.
2) Can the administrator transfer someone's tokens with id > 1?

**Comment by pasqu4le** [comment]
Answering your question:
1. correct, these other `token_id`s cannot be frozen/unfrozen, they can only be `transfer`red as per FA2.
2. Good question: I think we shouldn't.
    After all these additional tokens do not impact the "main" contract logic in any way and there may be use-cases where being outside of the admin's direct control may be desirable.
    On the other hand those that do want the admin to have control can always implement it by making him an operator, so it should not be a strong limitation for them.
