### ISSUE TITLE
Initialize LIGO version development

### ISSUE THREAD

**Issue by gromakovsky** [tqtezos/baseDAO#57]
# Clarification and motivation

We need to develop another version of BaseDAO: LIGO version of it. One difference between LIGO and Haskell/Indigo is that LIGO doesn't have compile-time polymorphism that Haskell has, there is no straightforward way to write a polymorphic contract that can be instantiated in compile-time (e. g. its type parameters). So configuration should happen in runtime.
Instead of type parameters we can use `map string bytes` or something similar. We can represent virtually any proposal type as such a map. E. g. if there are 2 fields `foo :: nat` and `bar :: bool`, we can represent it as a map with 2 keys (`"foo"` and `"bar"`) and values packed into `bytes`. We need to unpack them dynamically.

Since we have dynamic unpacking of type parameters, we can make other parameterization dynamic as well. For example, we can put decision lambda into storage instead of inlining it into contract code. This way we can have only one dynamic smart contract that is fully customizable without modification of source code.

Within this issue we shouldn't implement the whole contract (that would be too much), but create some ground on which we can build the contract.

# Acceptance criteria

1. There is a specification for the LIGO version of BaseDAO. Note that there are some substantial changes compared to the Lorentz version, but also they have a lot of stuff in common. So I am not sure how to structure it better (probably they should be in different files, but share common parts), please figure it out while working on the task.
2. There is a stub LIGO contract that is built by our CI and has a simple test-suite written in Haskell using `cleveland` (that also runs on CI).

**Comment by Martoon-00** [comment]
> Note that there are some substantial changes compared to the Lorentz version

There can I see them?

**Comment by gromakovsky** [comment]
They are not specified precisely, but the "Clarification and motivation" section gives some ideas. One of the goals of this issue is to specify them precisely.

The main change is that LIGO version will have dynamic types because it doesn't have static polymorphism (and sometimes compile-time polymorphism might be not desired).

**Comment by Martoon-00** [comment]
I see. So semantically we want the same thing, but code may differ, and so some interesting properties will arise.

**Comment by Martoon-00** [comment]
To achieve polymorphism, can't we proceed as follows?: have one `dao_config.ligo` file which will be the source of all DAO-custom logic, and all other modules of the contract will inline it.

In order to build the contract, we will put modules of baseDAO and `dao_config.ligo` into one folder. Makefile will hide all the building complexity. 

This seems to require just some small effort on providing the infra, and will let us write contracts normally.

**Comment by gromakovsky** [comment]
So we will have `dao_config_registry.ligo` and `dao_config_treasury.ligo`, right? And selecting the right DAO will be a matter of one `#include`. I think it can work, but an advantage of fully dynamic version is that it's easier to use from various UIs. I imagine that often it will be hard/undesirable to use `ligo` executable from UI and much easier to just convert application types to/from `map string bytes`, even at increased cost. So my idea was to kill two birds with one stone and have 2 versions:
1. One which focuses on performance: it's written in Lorentz and uses static configuration.
2. The other one is very dynamic and lets one do as much as possible after Michelson version of the contract is produced, but is more expensive. For this purpose LIGO can be more suitable.

Thus we have 2 versions with different properties and also use 2 languages as required.

**Comment by Martoon-00** [comment]
> So we will have dao_config_registry.ligo and dao_config_treasury.ligo, right? And selecting the right DAO will be a matter of one #include.

Yes.

Okay, I see. If it's not up to us, rather up to the UI to implement most of the DAO, then keeping proposal/extra as `map` should make sense.

**Comment by gromakovsky** [comment]
For UIs (and any use cases) where it's up to us, we can use the Lorentz version.

**Comment by pasqu4le** [comment]
@rinn7e since you are almost done with your LIGO issues, I reassigned this to you, there are two things left to do that need to be addressed by a new (closing) PR. We need to update the CI pipeline to:
- put the contract resulting from the `ligo` building step into the artifacts
- use that same contract to add a `test-ligo` step to run the tests as well
