### ISSUE TITLE
FA2 Batch Transfer as a Proposal Type

### ISSUE THREAD

**Issue by obstropolos** [tqtezos/baseDAO#66]
### Clarification and motivation

Enable a proposal to have multiple assets from a treasury sent to a single holder or multiple transactions to multiple individuals as a proposal

**Comment by pasqu4le** [comment]
Update: both requested proposal features are already implemented in TreasuryDAO, however we'd like to add this to RegistryDAO as well, which currently does not support transfers.

So this issue will be kept open with this additional acceptance criteria.
