### ISSUE TITLE
Cleanup Config

### ISSUE THREAD

**Issue by gromakovsky** [tqtezos/baseDAO#72]
# Clarification and motivation

1. We have `unfrozenTokenMetadata` and `frozenTokenMetadata`, but they are currently not used. Currently metadata is supposed to be in `sTokenAddress`. When we switch to TZIP-16 metadata, it will be stored differently, but it still won't be embedded into contract code. So I think it shouldn't be part of `Config`. `Config` contains everything necessary to produce a `.tz` file with smart contract code. Metadata is not needed for that, it's needed for origination.
2. AFAIU things like `daoName` and `daoDescription` are currently used only for documentation. They will also be part of metadata, but (see point above) this metadata won't be needed for the contract itself, it will go into storage.

# Acceptance criteria

1. Remove `unfrozenTokenMetadata` and `frozenTokenMetadata` from configuration.
2. Make it clearer that some configuration values are used only for documentation. I think we can keep them in one data type (`Config`), but let's at least provide comments.

**Comment by Martoon-00** [comment]
Note: the first point is done in #98.
