### ISSUE TITLE
Ensure sufficient lock-in from DAO participants

### ISSUE THREAD

**Issue by obstropolos** [tqtezos/baseDAO#75]
## Clarification and motivation

- freezing tokens puts them on a 1-full-cycle (voting+proposing) delay before they can be unfrozen
- tokens may be only be used for voting or proposing in the next period (either voting or proposing) after they are frozen
- freezing more tokens does not reset the delay to unfreeze tokens
- Would include two frozen tokens, one that's "freshly frozen" as of voting_period and the other that's been frozen long enough to unfreeze (without additional clearing time)

**Comment by pasqu4le** [comment]
Closing as all the points above have been solved by #140, which needed them for its logic.
