### ISSUE TITLE
Incorporate TZIP-16

### ISSUE THREAD

**Issue by gromakovsky** [tqtezos/baseDAO#80]
# Clarification and motivation

[TZIP-16](https://gitlab.com/tzip/tzip/-/blob/7671eb1fa5fdd0a56afa9387757f3a4a024cc2dc/proposals/tzip-16/tzip-16.md) specifies how to incorporate metadata into Michelson smart contracts. It requires `(big_map %metadata string bytes)` in the storage and specifies some standard fields that should be optionally provided.

We need it because:
1. Our original requirements say that `name` and `description` must be provided via TZIP-16 interface.
2. TZIP-12 will recommend using it soon, see https://gitlab.com/tzip/tzip/-/merge_requests/94.
3. We may want to attach additional metadata specific to certain DAOs (e. g. key and value types in Registry DAO).

# Acceptance criteria

1. Any BaseDAO contract satisfies TZIP-16 requirements (mandatory ones).
2. Our CLI exposes a command to print metadata JSON. We will use it for metadata that should be provided by our application, e. g. views. I guess it can be empty for now.

If you think there is something else related to TZIP-16 metadata that can be useful and implemented already, feel free to do it. Note: TZIP-12 metadata will be handled in #42.

**Comment by gromakovsky** [comment]
Take my comments in #42 into account. For example, I propose to store actual metadata in a separate contract. BaseDAO user needs such a separate contract. AFAIU it should be a trivial contract with `(big_map, unit)` storage and `FAILWITH` or `CDR; NIL operation; PAIR` implementation. Probably the best way to give such a contract to use is to add it to `morley-metadata` and provide another command in `baseDAO` CLI which would print that contract.

**Comment by Martoon-00** [comment]
CI now should pass, and the requested changes should be addressed.
