### ISSUE TITLE
Improve handling of failed proposals

### ISSUE THREAD

**Issue by gromakovsky** [tqtezos/baseDAO#87]
# Clarification and motivation

This task follows #69. The broader problem is described [here](https://gist.github.com/gromakovsky/cd03f73f1f5dcc9640def18d0eee642d) along with a proposed solution. We are going to discuss it, reach consensus about the best solution and implement it.

# Acceptance criteria

Once there is a consensus for the problem described in the aforementioned gist document, we should implement the solution we agree upon.

**Comment by pasqu4le** [comment]
Consensus has been reached on a new solution, these can be considered new acceptance criteria:

- A new `proposal_flush_time: seconds` is stored in the contract
    - it must be bigger than the `voting_period`
    - this value is fixed and provided at origination
    - proposals cannot be flushed until `proposal_flush_time` has passed from their submission
- A new `proposal_expired_time: seconds` is stored in the contract
    - it must be bigger than the `proposal_flush_time`
    - this value is fixed and provided at origination
    - proposals cannot be flushed after `proposal_expired_time` has passed from their submission
- A new `guardian` role exists, the address for it is stored in the contract
    - this value is fixed and provided at origination
    - this cannot be held by an implicit account (to be checked in `drop_proposal`)
    - its permissions are different from the `admin`s, it's duties are only to call `drop_proposal` where necessary 

- `drop_proposal` has a new behavior:
    - it can be called on a proposal by its proposer at any time
    - it cannot be called by the `admin` in any special way (only as any other user)
    - it can be called on any proposal that has passed the `proposal_expired_time` by anyone
    - if called on an expired proposal, the paid fee is not returned to the proposer
    - the `guardian` can call this on any proposals at any time
        - this call will check that the `guardian` is not an implicit account, aka `SENDER` is not `SOURCE`
