### ISSUE TITLE
Revise and restore checks applying to most entrypoints

### ISSUE THREAD

**Issue by gromakovsky** [tqtezos/baseDAO#91]
# Clarification and motivation

There are 2 checks we want to make in most of entrypoints: `ensureZeroTransfer` and `ensureNotMigrated`.
In #85 we temporarily disabled `ensureZeroTransfer` because it's tricky to do it for everything besides `CallCustom` without copy-pasting it everywhere. And we don't need this check in `CallCustom` because in some custom entrypoints we want to permit XTZ transfers.

Apart from that `ensureNotMigrated` seems to be copy-pasted in many places, but we can do it only once and it should be more efficient.

# Acceptance criteria

1. `ensureZeroTransfer` is restored and called for all entrypoints besides `CallCustom`. Probably we need to restructure the parameter type and then do just one `IF_LEFT {} {ensureZeroTransfer}`.
2. `ensureNotMigrated` appears only once (or maybe twice or so) in the contract code. Perhaps a similar restructuring should be made to achieve that.

**Comment by Martoon-00** [comment]
Interesting, how will we make sure that the user _does_ call `ensureZeroTransfer` and `ensureNotMigrated` in his custom entrypoints unless they are not necessary. For instance, in TreasuryDAO's `%default` we probably want to call `ensureNotMigrated`, but it is too easy to forget about.

**Comment by gromakovsky** [comment]
Currently I don't see a way other than saying "please be careful".

**Comment by gromakovsky** [comment]
I think we can also expand the configuration to include things like `permitXtzTransfer :: Bool`. E. g. for TreasuryDAO it's probably harmless to permit non-zero amount in any entrypoint because they won't be locked.

**Comment by Martoon-00** [comment]
:pogchamp: That would be the simplest way.

**Comment by gromakovsky** [comment]
One more thing to consider: currently we want to prohibit non-zero XTZ transfers in all entrypoints, including `propose`, however, sometimes it can be useful to transfer non-zero amount of XTZ in `propose`, for example it can be useful for #67 where we want to have fees in Tez.

**Comment by pasqu4le** [comment]
Update on this issue's status.

The current contract (LIGO-only version) no longer has the migration functionality (see #173), which invalidates/cover point 2.

Regarding the n.1 acceptance criteria the contract already makes the no-xtz check only once as the overall parameter is divided in entrypoints that do/don't accept them.

The only point left is to decide on what entrypoints we want to keep the no-xtz check and on which we don't, given some new discussions on the matter I opened #256 for it.

So, everything from this issue has either already been covered or will be by #256, hence why I'm closing this.
