### ISSUE TITLE
Add token_address off-chain view

### ISSUE THREAD

**Issue by gromakovsky** [tqtezos/baseDAO#92]
# Clarification and motivation

We used to have a `token_address` entrypoint, but we removed it in #85 because it's not very useful. We can instead make it an off-chain view (according to TZIP-16).

# Acceptance criteria

Metadata printed by the `print-metadata` command includes `token_address` off-chain view.

**Comment by pasqu4le** [comment]
Note: This should be delay to after #169 as the metadata should be created based on the Ligo version only (including this new off-chain view)
